language: python
cache: pip

matrix:
  include:
   - env: TOXENV=py27-dj18-wt17
     python: 2.7
   - env: TOXENV=py27-dj18-wt18
     python: 2.7
   - env: TOXENV=py27-dj19-wt19
     python: 2.7
   - env: TOXENV=py27-dj110-wt110
     python: 2.7
   - env: TOXENV=py27-dj110-wt111
     python: 2.7
   - env: TOXENV=py27-dj111-wt112
     python: 2.7
   - env: TOXENV=py27-dj111-wt113
     python: 2.7
   - env: TOXENV=py34-dj111-wt113
     python: 3.4
   - env: TOXENV=py35-dj111-wt21
     python: 3.5
   - env: TOXENV=py35-dj20-wt20
     python: 3.5
   - env: TOXENV=py36-dj20-wt21
     python: 3.6
   - env: TOXENV=py36-dj20-wt22
     python: 3.6
   - env: TOXENV=py36-dj21-wt23
     python: 3.6

# Package installation
install:
  - pip install tox

# Run the tests
script:
  tox
